---
title: "Final Project Proposal"
date: "2025-10-31"
output: github_document
---

## Director, Genre, and Duration: The Secret to Higher Film Ratings
*Satya Batna (ssb2231), Ruby He (yh3824), Nicolette Lim (nrl2142), Amanda Sy (ars2376), Kallan Roan (kr3145)*

### Motivation 
We are a group of passionate movie enthusiasts who are eager to dive into the Letterboxd dataset to uncover fascinating insights about films. In an era dominated by short-form content and claims of shorter attention spans, we are curious to see if shorter movies tend to receive higher ratings. We also want to explore the secret formulas behind top-rated films: Do certain directors excel when they stick to a specific genre or keep their films under 90 minutes? Beyond that, we are excited to analyze trends in genre preferences and discover what kind of film would captivate audiences. 

### Final Products 

Final products will be a written report, webpage, and screencast. The report will describe an overview of the project, initial questions about the topic, the data collection and cleaning process, exploratory analyses, a discussion of our results, and any changes we made to our project over time. The second product will be a webpage that is easily accessible to a broad audience and gives a summary of the project scope, data, approaches, visualizations, and other results. The last product will be a two-minute narrated screencast that illustrates our project using relevant visual aids.

### Data Source 

We will be using this [Letterbox Movie Classification](https://www.kaggle.com/datasets/sahilislam007/letterbox-movie-classification-dataset) dataset from [Kaggle](https://www.kaggle.com/). It has 10,002 observations with 17 variables. Variables that we may be interested in investigating include genre, director, runtime, rating, watches, and likes. 

### Anticipated Analyses/Visualizations/Coding Challenges

Exploratory analyses will identify patterns and potential relationships among variables such as average ratings, likes, watches, list appearances, and runtime across genres, studios, and directors. These will be visualized using box plots, bar plots, histograms, and scatter plots. Bar plots will be used to explore which directors are associated with the most movies or film genres. 

Statistical analyses using linear regression will identify which predictors are significantly associated with film ratings, and assess whether they vary by directors, genres, or runtime. More specifically, we will test whether the associations between genres or runtime (under 90 minutes) and ratings vary across directors. We will also test which predictors are significantly associated with a film’s number of list appearances.

A main coding challenge is navigating data cleaning for analyses. Some variables, such as directors, genres, and studios, can contain multiple values nested inside a signal cell for each film. We would need to clean the dataset to ensure each cell contains a singular, scalar value for analysis. Additional data cleaning steps include ensuring our data is in a long format and managing missing values for key variables. 

### Timeline

<u>**Oct 30th @ 8 pm**</u> – Initial Group Meeting via Teams Meeting

* Decide on Proposal Topic
* Decide on the Dataset
* Split up Tasks

<u>**Nov 6th**</u> – Group Check-in via Chat

* Troubleshoot any last-minute details
* Confirmation from all group members about their sections

<u>**Nov 7th @ 1pm – Proposal Due**</u>

<u>**Nov 10th–14th**</u> – Zoom Meeting for Project Review

<u>**Nov 15th**</u> – Short Team Meeting

* Division of Tasks

<u>**Nov 21st @ 9pm**</u> – Team Meeting for Troubleshooting

<u>**Nov 30th @ 8pm**</u> – Meeting for Video

<u>**Dec 5th @ 5pm**</u> – Team Meeting for Wrap-Up

* Final Troubleshooting
* Completion of Contributions Page

<u>**Dec 6th @ 11:59 pm – Project Submission**</u>

* Written report giving a detailed project description
* Webpage overview of the project, with a short explanatory video (published online)
* Brief assessment of your teammates' contributions (as a short document)

<u>**Dec 11th @ 10 am**</u> – In-class discussion of final projects

Office Hours will be attended by group members as necessary, and all answers will be reported to group members who were unable to attend. Any conflicts with the schedule will be discussed at least 24 hours before the meeting. 


