---
title: "Regression Analysis"
output: 
  html_document:
    toc: true
    toc_float: true
---

```{r message = FALSE}
library(tidyverse)
library(mgcv)
library(modelr)
library(glmnet)
library(plotly)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

set.seed(1)
```

Import data and organize genre 
```{r}
movie_df = read.csv("data/letterbox_movie_classification_dataset.csv") |>
  janitor::clean_names() |>
  filter(original_language == "English") |>
  select(film_title, director, average_rating, genres, runtime, original_language, description, studios, watches, list_appearances, likes, fans, lowest, medium, highest, total_ratings)
```

```{r}
genre_df = movie_df |>
  mutate(genres = str_remove_all(genres, "\\[|\\]|'")) |>
  separate_rows(genres, sep = ",\\s*")
```

```{r}
genre_wide = genre_df |> 
  mutate(
    studios = as.character(studios),
    description = as.character(description),
    genres = as.character(genres)
  ) |> 
  mutate(value = 1) |> 
  group_by(
    film_title, director, average_rating, runtime, original_language,
    description, studios, watches, list_appearances, likes, fans,
    lowest, medium, highest, total_ratings, genres
  ) |> 
  summarise(value = max(value), .groups = "drop") |>
  pivot_wider(
    id_cols = c(
      film_title, director, average_rating, runtime, original_language,
      description, studios, watches, list_appearances, likes, fans,
      lowest, medium, highest, total_ratings
    ),
    names_from = genres,
    values_from = value,
    values_fill = 0
  ) |> 
  janitor::clean_names()
```

# Linear Models

## Runtime vs. Average Rating
```{r}
# Scatterplot 
movie_df |> 
  ggplot(aes(runtime, average_rating)) +
  geom_point(alpha = 0.6) +
  geom_smooth(method = "lm", se = TRUE) +
  labs(
    title = "Relationship Between Runtime and Average Rating",
    x = "Runtime (minutes)",
    y = "Average Rating"
  )

runtime_model = lm(average_rating ~ runtime, data = movie_df)

#Hypothesis Test
runtime_model |> 
  broom::tidy() |> 
  select(term, estimate, p.value)

```
WRITE INTREPRATION
## Runtime vs. Average Rating, adjusted for covariates
```{r}

runtime_adj_model = lm(
  average_rating ~ runtime + watches + list_appearances + fans,
  data = movie_df
)

runtime_adj_model |> 
  broom::tidy() |> 
  select(term, estimate, p.value)

```
WRITE INTERPRETATION

## Appearances in User-Curated Lists vs. Average Rating
```{r}
movie_df |> 
  ggplot(aes(list_appearances, average_rating)) +
  geom_point() +
  geom_smooth(method = "lm", se = TRUE)

appearances_model = lm(average_rating ~ list_appearances, data = movie_df)

appearances_model |> 
  broom::tidy() |> 
  select(term, estimate, p.value)
```

## Total Watches vs. Average Rating
```{r}
movie_df |> 
  ggplot(aes(watches, average_rating)) +
  geom_point() +
  geom_smooth(method = "lm", se = TRUE)

watches_model = lm(average_rating ~ watches, data = movie_df)

watches_model |> 
  broom::tidy() |> 
  select(term, estimate, p.value)
```

## Fans vs. Average Rating
```{r}
movie_df |> 
  ggplot(aes(fans, average_rating)) +
  geom_point() +
  geom_smooth(method = "lm", se = TRUE) +
  scale_x_log10()

fans_model = lm(average_rating ~ fans, data = movie_df) 

fans_model |> 
  broom::tidy() |> 
  select(term, estimate, p.value)
```

